/**
 * Module F — i18n runtime provider.
 *
 * Sets up a per-request Lingui i18n instance (never the shared singleton)
 * and wraps children with both `I18nProvider` (Lingui) and `LocaleContext`.
 *
 * Both catalogs (en + de) are bundled statically so language switching has
 * zero network wait and SSR stays simple.
 *
 * The resolved locale + currency come from the root loader data (derived from
 * cookie / Accept-Language / DB preference on the server), so both the server
 * render and the client hydration activate the same catalog — no hydration
 * mismatch.
 *
 * Issue 02: the provider is now client-stateful. `useState` is seeded from the
 * server-resolved props so SSR and first client render are identical. Calling
 * `setPreferences` updates state, re-activates the catalog (live re-render of
 * all `<Trans>` nodes), sets `document.documentElement.lang`, and fires the
 * persistence mutation in the background.
 */

"use client";

import { setupI18n } from "@lingui/core";
import { I18nProvider } from "@lingui/react";
import type { ReactNode } from "react";
import { useState } from "react";
import type { SupportedCurrency, SupportedLocale } from "#/i18n/config";
import { LocaleContext } from "#/i18n/locale-context";

// Static catalog imports — both locales bundled at build time.
// These are generated by `pnpm compile`; paths must match lingui.config.ts.
import { messages as deMessages } from "#/locales/de/messages";
import { messages as enMessages } from "#/locales/en/messages";

const CATALOGS = {
	en: enMessages,
	de: deMessages,
} as const;

/**
 * Build a fresh per-call i18n instance with both catalogs loaded and the given
 * locale activated. Creating a new instance each time avoids mutating a shared
 * singleton — critical for SSR isolation across concurrent requests.
 */
function buildI18n(locale: SupportedLocale) {
	const i18n = setupI18n();
	i18n.load(CATALOGS);
	i18n.activate(locale);
	return i18n;
}

interface I18nSetupProviderProps {
	locale: SupportedLocale;
	currency: SupportedCurrency;
	/** Called when the user switches language/currency so the mutation can be fired. */
	onSetPreferences?: (next: {
		locale?: SupportedLocale;
		currency?: SupportedCurrency;
	}) => void;
	children: ReactNode;
}

/**
 * Client-stateful i18n provider.
 *
 * Seed strategy: `useState` is initialised from the server-resolved `locale` +
 * `currency` props. Both the server render and the first client hydration render
 * use the same values (passed from the root loader), so there is no hydration
 * mismatch. Subsequent updates come via `setPreferences`.
 *
 * `<html lang>` lives in the shell outside the React subtree, so it is updated
 * imperatively (a legitimate DOM-sync in an event-handler path, not a `useEffect`).
 */
export function I18nSetupProvider({
	locale: initialLocale,
	currency: initialCurrency,
	onSetPreferences,
	children,
}: I18nSetupProviderProps) {
	// Seeded from server-resolved props — identical on both server and client first
	// render, which is the hydration-parity guarantee.
	const [state, setState] = useState(() => ({
		locale: initialLocale,
		currency: initialCurrency,
	}));

	// Build a fresh i18n instance keyed to the current locale. This is done
	// synchronously during render (not in an effect) so the correct catalog is
	// active for the current render pass — both on SSR and on client updates.
	const i18n = buildI18n(state.locale);

	function setPreferences(next: {
		locale?: SupportedLocale;
		currency?: SupportedCurrency;
	}) {
		const newLocale = next.locale ?? state.locale;
		const newCurrency = next.currency ?? state.currency;

		// 1. Instant client re-render — the new state flows into buildI18n() on
		//    the next render pass, activating the right catalog.
		setState({ locale: newLocale, currency: newCurrency });

		// 2. Sync <html lang> — this element lives in the shell outside the React
		//    tree and won't follow client state otherwise. Updating it here (in an
		//    event-handler callsite) is the correct imperative DOM sync pattern.
		if (typeof document !== "undefined" && next.locale !== undefined) {
			document.documentElement.lang = next.locale;
		}

		// 3. Persist to DB + sync cookies in the background (non-blocking).
		onSetPreferences?.(next);
	}

	return (
		<I18nProvider i18n={i18n}>
			<LocaleContext.Provider
				value={{
					locale: state.locale,
					currency: state.currency,
					setPreferences,
				}}
			>
				{children}
			</LocaleContext.Provider>
		</I18nProvider>
	);
}
