/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedHabitsRouteImport } from './routes/_authed/habits'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedWorkoutsIndexRouteImport } from './routes/_authed/workouts.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedWorkoutsActiveRouteImport } from './routes/_authed/workouts.active'
import { Route as AuthedWorkoutsHistoryIndexRouteImport } from './routes/_authed/workouts.history.index'
import { Route as AuthedWorkoutsRoutinesNewRouteImport } from './routes/_authed/workouts.routines.new'
import { Route as AuthedWorkoutsHistoryWorkoutIdRouteImport } from './routes/_authed/workouts.history.$workoutId'
import { Route as AuthedWorkoutsExercisesExerciseIdRouteImport } from './routes/_authed/workouts.exercises.$exerciseId'
import { Route as AuthedWorkoutsRoutinesRoutineIdEditRouteImport } from './routes/_authed/workouts.routines.$routineId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHabitsRoute = AuthedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsIndexRoute = AuthedWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkoutsActiveRoute = AuthedWorkoutsActiveRouteImport.update({
  id: '/workouts/active',
  path: '/workouts/active',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsHistoryIndexRoute =
  AuthedWorkoutsHistoryIndexRouteImport.update({
    id: '/workouts/history/',
    path: '/workouts/history/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkoutsRoutinesNewRoute =
  AuthedWorkoutsRoutinesNewRouteImport.update({
    id: '/workouts/routines/new',
    path: '/workouts/routines/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkoutsHistoryWorkoutIdRoute =
  AuthedWorkoutsHistoryWorkoutIdRouteImport.update({
    id: '/workouts/history/$workoutId',
    path: '/workouts/history/$workoutId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkoutsExercisesExerciseIdRoute =
  AuthedWorkoutsExercisesExerciseIdRouteImport.update({
    id: '/workouts/exercises/$exerciseId',
    path: '/workouts/exercises/$exerciseId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkoutsRoutinesRoutineIdEditRoute =
  AuthedWorkoutsRoutinesRoutineIdEditRouteImport.update({
    id: '/workouts/routines/$routineId/edit',
    path: '/workouts/routines/$routineId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/habits': typeof AuthedHabitsRoute
  '/history': typeof AuthedHistoryRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/settings': typeof AuthedSettingsRoute
  '/workouts/active': typeof AuthedWorkoutsActiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/workouts/': typeof AuthedWorkoutsIndexRoute
  '/workouts/exercises/$exerciseId': typeof AuthedWorkoutsExercisesExerciseIdRoute
  '/workouts/history/$workoutId': typeof AuthedWorkoutsHistoryWorkoutIdRoute
  '/workouts/routines/new': typeof AuthedWorkoutsRoutinesNewRoute
  '/workouts/history/': typeof AuthedWorkoutsHistoryIndexRoute
  '/workouts/routines/$routineId/edit': typeof AuthedWorkoutsRoutinesRoutineIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/habits': typeof AuthedHabitsRoute
  '/history': typeof AuthedHistoryRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/workouts/active': typeof AuthedWorkoutsActiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/workouts': typeof AuthedWorkoutsIndexRoute
  '/workouts/exercises/$exerciseId': typeof AuthedWorkoutsExercisesExerciseIdRoute
  '/workouts/history/$workoutId': typeof AuthedWorkoutsHistoryWorkoutIdRoute
  '/workouts/routines/new': typeof AuthedWorkoutsRoutinesNewRoute
  '/workouts/history': typeof AuthedWorkoutsHistoryIndexRoute
  '/workouts/routines/$routineId/edit': typeof AuthedWorkoutsRoutinesRoutineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/habits': typeof AuthedHabitsRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/workouts/active': typeof AuthedWorkoutsActiveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/workouts/': typeof AuthedWorkoutsIndexRoute
  '/_authed/workouts/exercises/$exerciseId': typeof AuthedWorkoutsExercisesExerciseIdRoute
  '/_authed/workouts/history/$workoutId': typeof AuthedWorkoutsHistoryWorkoutIdRoute
  '/_authed/workouts/routines/new': typeof AuthedWorkoutsRoutinesNewRoute
  '/_authed/workouts/history/': typeof AuthedWorkoutsHistoryIndexRoute
  '/_authed/workouts/routines/$routineId/edit': typeof AuthedWorkoutsRoutinesRoutineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/habits'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/workouts/active'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/workouts/'
    | '/workouts/exercises/$exerciseId'
    | '/workouts/history/$workoutId'
    | '/workouts/routines/new'
    | '/workouts/history/'
    | '/workouts/routines/$routineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/habits'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/'
    | '/workouts/active'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/workouts'
    | '/workouts/exercises/$exerciseId'
    | '/workouts/history/$workoutId'
    | '/workouts/routines/new'
    | '/workouts/history'
    | '/workouts/routines/$routineId/edit'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/habits'
    | '/_authed/history'
    | '/_authed/onboarding'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/workouts/active'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/workouts/'
    | '/_authed/workouts/exercises/$exerciseId'
    | '/_authed/workouts/history/$workoutId'
    | '/_authed/workouts/routines/new'
    | '/_authed/workouts/history/'
    | '/_authed/workouts/routines/$routineId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/habits': {
      id: '/_authed/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthedHabitsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/': {
      id: '/_authed/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthedWorkoutsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workouts/active': {
      id: '/_authed/workouts/active'
      path: '/workouts/active'
      fullPath: '/workouts/active'
      preLoaderRoute: typeof AuthedWorkoutsActiveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/history/': {
      id: '/_authed/workouts/history/'
      path: '/workouts/history'
      fullPath: '/workouts/history/'
      preLoaderRoute: typeof AuthedWorkoutsHistoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/routines/new': {
      id: '/_authed/workouts/routines/new'
      path: '/workouts/routines/new'
      fullPath: '/workouts/routines/new'
      preLoaderRoute: typeof AuthedWorkoutsRoutinesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/history/$workoutId': {
      id: '/_authed/workouts/history/$workoutId'
      path: '/workouts/history/$workoutId'
      fullPath: '/workouts/history/$workoutId'
      preLoaderRoute: typeof AuthedWorkoutsHistoryWorkoutIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/exercises/$exerciseId': {
      id: '/_authed/workouts/exercises/$exerciseId'
      path: '/workouts/exercises/$exerciseId'
      fullPath: '/workouts/exercises/$exerciseId'
      preLoaderRoute: typeof AuthedWorkoutsExercisesExerciseIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/routines/$routineId/edit': {
      id: '/_authed/workouts/routines/$routineId/edit'
      path: '/workouts/routines/$routineId/edit'
      fullPath: '/workouts/routines/$routineId/edit'
      preLoaderRoute: typeof AuthedWorkoutsRoutinesRoutineIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHabitsRoute: typeof AuthedHabitsRoute
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWorkoutsActiveRoute: typeof AuthedWorkoutsActiveRoute
  AuthedWorkoutsIndexRoute: typeof AuthedWorkoutsIndexRoute
  AuthedWorkoutsExercisesExerciseIdRoute: typeof AuthedWorkoutsExercisesExerciseIdRoute
  AuthedWorkoutsHistoryWorkoutIdRoute: typeof AuthedWorkoutsHistoryWorkoutIdRoute
  AuthedWorkoutsRoutinesNewRoute: typeof AuthedWorkoutsRoutinesNewRoute
  AuthedWorkoutsHistoryIndexRoute: typeof AuthedWorkoutsHistoryIndexRoute
  AuthedWorkoutsRoutinesRoutineIdEditRoute: typeof AuthedWorkoutsRoutinesRoutineIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHabitsRoute: AuthedHabitsRoute,
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWorkoutsActiveRoute: AuthedWorkoutsActiveRoute,
  AuthedWorkoutsIndexRoute: AuthedWorkoutsIndexRoute,
  AuthedWorkoutsExercisesExerciseIdRoute:
    AuthedWorkoutsExercisesExerciseIdRoute,
  AuthedWorkoutsHistoryWorkoutIdRoute: AuthedWorkoutsHistoryWorkoutIdRoute,
  AuthedWorkoutsRoutinesNewRoute: AuthedWorkoutsRoutinesNewRoute,
  AuthedWorkoutsHistoryIndexRoute: AuthedWorkoutsHistoryIndexRoute,
  AuthedWorkoutsRoutinesRoutineIdEditRoute:
    AuthedWorkoutsRoutinesRoutineIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
